### ISSUE TITLE
Where exactly is the source?

### ISSUE THREAD

**Issue by AlirezaChegini** [charles2gan/GDA-android-reversing-Tool#1]
In each [release](https://github.com/charles2gan/GDA-android-reversing-Tool/releases/), you write the **Source code (zip)** but in fact, there is no code source!
Can you explain?
I'm a user and a fan of your program and also like to read the source code.

**Comment by charles2gan** [comment]
I'm not ready to release the source code yet. it's still messy and look like the accident scene. So wait till I have time! ^.-

**Comment by AlirezaChegini** [comment]
If I want to participate in the development, a messy code is not a problem :)
_ As you wish_

**Comment by 2191265529** [comment]
wait to open source

**Comment by GSharma789** [comment]
please open source it . too much excitement to see its code

**Comment by socialAPIS** [comment]
Seriously, really good program!
I had a wish if the program could change the dex file and compile it in the apk file, that would be wonderful

**Comment by CalebFenton** [comment]
Please [don't worry about messy code](https://www.youtube.com/watch?v=0SARbwvhupQ). It's not art. No one will judge you. Most won't even read the README. ;)

Your project looks really cool, and I'd like to understand how it works better, but can't. I'm also hesitant to run a random, packed executable on my machine. I'd feel much safer auditing the code and compiling it myself.

**Comment by Surendrajat** [comment]
@charles2gan if you don't have any intention of monetizing this tool, please considering open sourcing it(messy is better than nothing). It'll help the community as a base to build a complete android RE platform, which is still like a dream for people who can't pay $$$$$ to JEB/IDA.

**Comment by apkunpacker** [comment]
really waiting for open source code

**Comment by ronmazor** [comment]
What is the difference between the pro version and the regular version and how can I pay for the pro version I sent few emails and I got no answers

**Comment by charles2gan** [comment]
> What is the difference between the pro version and the regular version and how can I pay for the pro version I sent few emails and I got no answers
try this
http://www.gda.wiki:9090/buy.php
