### ISSUE TITLE
反编译超大方法失败

### ISSUE THREAD

**Issue by ihbing** [charles2gan/GDA-android-reversing-Tool#10]
![image](https://user-images.githubusercontent.com/27600008/73729814-afd36f00-4770-11ea-8039-d1d3d002d665.png)
样本:QQ邮箱5.7.2
下载地址:https://www.wandoujia.com/apps/246975

**Comment by charles2gan** [comment]
thanks，I will do with it later。

**Comment by charles2gan** [comment]
> ![image](https://user-images.githubusercontent.com/27600008/73729814-afd36f00-4770-11ea-8039-d1d3d002d665.png)
> 样本:QQ邮箱5.7.2
> 下载地址:https://www.wandoujia.com/apps/246975

感谢提供bug反馈，下一个版本更新：
![111](https://user-images.githubusercontent.com/13128580/74009364-f79b0600-49bd-11ea-9073-e0827ed297e5.png)

**Comment by ihbing** [comment]
谢谢，更新很及时，赞一个
