### ISSUE TITLE
decode unicode hex string to readable string

### ISSUE THREAD

**Issue by thegoder66** [charles2gan/GDA-android-reversing-Tool#104]
is there any option to decode hex string to readable format?

🎈 Config->De-obfuscate is not working.

![apk](https://user-images.githubusercontent.com/109083202/178271533-cd4772e0-019d-4ab2-8bb8-3f13018d4d95.png)

**Comment by charles2gan** [comment]
I am going to add the options for strings. the problem is caused by the unchecked out language of strings.
