### ISSUE TITLE
GDA Crash

### ISSUE THREAD

**Issue by apkunpacker** [charles2gan/GDA-android-reversing-Tool#11]
Step to reproduce:

1: open any dex and use python script
2.: again use python script
3: gda crash with error

**Comment by charles2gan** [comment]
No, Can not reproduce the error, you should tell the more details, or upload your python script.

**Comment by apkunpacker** [comment]
I am using example-8-strdcr2.py

**Comment by charles2gan** [comment]
> I am using example-8-strdcr2.py

The sample will work for a malware, I will fix the bug of crash
