### ISSUE TITLE
frida功能不能使用

### ISSUE THREAD

**Issue by hackren** [charles2gan/GDA-android-reversing-Tool#110]
已在手机端运行   Frida-Server 15.1.8
但是执行某个hook或者脚本时总是如下提示
   ____
    / _  |   Frida 15.1.8 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
Spawning `--no-pause`...
Failed to spawn: unable to find application with identifier '--no-pause'

**Comment by hackren** [comment]
我大概知道是因为GDA无法识别出我apk的包名，所以提示以上错误信息。
希望能提供一个手动指定包名的功能，以便在一些加壳apk或者脱壳后的dex里能使用frida的相关功能

**Comment by charles2gan** [comment]
提供下你的apk文件，方便我调试。

**Comment by CtrlAltDelet** [comment]
好像新版frida 移除了--no-pause吧，我看frida -h里边没有这个

**Comment by CtrlAltDelet** [comment]
https://github.com/frida/frida/issues/2277
先用旧版的吧

**Comment by charles2gan** [comment]
> [frida/frida#2277](https://github.com/frida/frida/issues/2277) 先用旧版的吧
谢谢，下个版本做个更新。

**Comment by kbamol** [comment]
@charles2gan  In GDA 4.03 I found issue regarding frida. As in new frida the application is no longer paused by default on start-up. And when I tried to hook in GDA it gives me unrecognized arguments: --no-pause this error.

**Comment by charles2gan** [comment]
> @charles2gan In GDA 4.03 I found issue regarding frida. As in new frida the application is no longer paused by default on start-up. And when I tried to hook in GDA it gives me unrecognized arguments: --no-pause this error.

this bug will be fixed in the next version.
