### ISSUE TITLE
双击跳转时程序崩溃，尝试多次都会崩溃  bug?

### ISSUE THREAD

**Issue by anylayer** [charles2gan/GDA-android-reversing-Tool#112]
gda version: 4.02

package: com.tencent.mm 
version: 8.0.27

复现步骤：
在com.tencent.mm.plugin.webview.jsapi.q下点击com.tencent.mm.plugin.webview.jsapi.a后就会崩溃
![image](https://user-images.githubusercontent.com/46556817/190612006-f89fb4f5-5dd6-4bbd-aa61-3a80affc824a.png)

**Comment by charles2gan** [comment]
感谢反馈，bug已修复，下个版本见。
