### ISSUE TITLE
旧版能打开的dex新版打不开了

### ISSUE THREAD

**Issue by lies2020** [charles2gan/GDA-android-reversing-Tool#114]
![2022-10-29_103710](https://user-images.githubusercontent.com/78834996/198781862-58ca591e-044a-40a4-a6f1-9f94baa850d6.jpg)
找了个3.96的版本可以打开，之后的版本就是上面的提示
[dex.zip](https://github.com/charles2gan/GDA-android-reversing-Tool/files/9893335/dex.zip)

**Comment by lies2020** [comment]
本来以为文件头有问题，用16进制打开看了一下，classes.dex本来就没有什么代码，直接打开classes2.dex就没有问题了

**Comment by charles2gan** [comment]
谢谢反馈，加入修复列表。
