### ISSUE TITLE
Can't open dex/jar in GDA4.0.3

### ISSUE THREAD

**Issue by aabbccgg** [charles2gan/GDA-android-reversing-Tool#115]
The latest version GDA4.0.3 can't open dex or jar file, although the header of the file  is correct.
When trying to open the jar file, GDA said: dx cannot process current jar, please check it.
But it works well with GDA 4.0.2. So I think it's a bug, please fix it thx. :)

**Comment by charles2gan** [comment]
thx, I will check it. can you share your jar and dex files with me for debugging?
