### ISSUE TITLE
反混淆后包名变得不可识别，并且点击里面的方法不能切换代码

### ISSUE THREAD

**Issue by lies2020** [charles2gan/GDA-android-reversing-Tool#117]
今天反编译太极APP，反混淆后原来可识别的完包名完全看不懂了，并且代码停留在混淆前的方法处，点击别的方法不能切换过去
APP下载地址：https://taichi.cool/zh/download.html

反混淆前：
![1](https://user-images.githubusercontent.com/78834996/205633743-4a233631-3b2f-4338-89d9-85ae28942070.jpg)

反混淆后：
![2](https://user-images.githubusercontent.com/78834996/205633763-8feea8b9-77fe-4d47-a78b-42bfd44b1338.jpg)

**Comment by charles2gan** [comment]
感谢反馈，该bug已经修复，敬请关注GDA4.04.
