### ISSUE TITLE
AndroidManifest.xml反编译问题

### ISSUE THREAD

**Issue by yangjiashun-bst** [charles2gan/GDA-android-reversing-Tool#120]
[https://drive.google.com/file/d/1SDET0F5js5nOtwhdVxz20dpMZ_mGVYBB/view?usp=share_link](url)
用GDA反编译出来配置项都是数字
![QQ截图20221216093639](https://user-images.githubusercontent.com/103926735/208002152-9df5f052-eb75-4a1c-a03a-e90ea616bd14.png)
用apktool反编译出来是正常的
![QQ截图20221216094145](https://user-images.githubusercontent.com/103926735/208002503-ea5738ff-04aa-4fe7-a77e-4cb4afca90fc.png)

**Comment by charles2gan** [comment]
感谢反馈，那是资源ID，apktool解析这个文件时，把相应资源ID替换了，后续可以对此做下优化。
