### ISSUE TITLE
4.04 BUG反馈

### ISSUE THREAD

**Issue by SeeFlowerX** [charles2gan/GDA-android-reversing-Tool#123]
版本：4.04

样本： [weixin8016android2040_arm64.apk](https://dldir1.qq.com/weixin/android/weixin8016android2040_arm64.apk)

方法：com.tencent.xweb.XWebCoreContentProvider.openFile

在如图所示的地方出现了错误

![image](https://user-images.githubusercontent.com/70688581/211713164-de4121e5-0967-4be9-9090-3624db7116c1.png)

smali内容请[点此](https://gist.github.com/SeeFlowerX/e88aa5d1333b9e8391a3e1070b1fb8c4)

补充信息：

- 经过测试，对于该样本，4.02没有出现这个问题
- 4.04在加载该样本时有较大几率卡住，并且在99%的时候必定卡住，然后等一会儿弹出30s balala...，不过这个时候点取消还是可以查看

**Comment by charles2gan** [comment]
感谢，已加入修复清单！
