### ISSUE TITLE
404版本 类中没有field成员, 反编译失败

### ISSUE THREAD

**Issue by hide955** [charles2gan/GDA-android-reversing-Tool#126]
类中没有field成员, 反编译dex失败

**Comment by charles2gan** [comment]
Open issue时，需提供有效的bug信息。

**Comment by hide955** [comment]
[classes.zip](https://github.com/charles2gan/GDA-android-reversing-Tool/files/10672471/classes.zip)
这是测试例子

**Comment by charles2gan** [comment]
GDA在对DEX文件验证时，检测到fieldIdsSize=0，导致文件无法验证通过，我已经对此进行了纠正。请关注下一个更新版本。
