### ISSUE TITLE
Selecting Text

### ISSUE THREAD

**Issue by Nerixyz** [charles2gan/GDA-android-reversing-Tool#13]
This isn't an important feature, but it would be nice if one could double click on text and have it selected like in other editors.

**Comment by charles2gan** [comment]
where

**Comment by Nerixyz** [comment]
@charles2gan Basically everywhere where you can select text. But most importantly in the main code viewer.

**Comment by charles2gan** [comment]
@Nerixyz "double-click" has been used for a jump of class, method, and field in the code viewer.
