### ISSUE TITLE
关于apk反编译重新打包后包名解析不对

### ISSUE THREAD

**Issue by dorry2015** [charles2gan/GDA-android-reversing-Tool#132]
利用apktool反编译apk修改包名后包名解析的还是修改前的包名，jadx解析没有问题
修改了反编译后的smali文件夹名字后gda解析的还是以前的包名，.smali文件本人也修改了的
如图
![image](https://user-images.githubusercontent.com/3806357/225180243-c18176d3-f1f7-45ce-9a27-38691961f3f9.png)
![image](https://user-images.githubusercontent.com/3806357/225180411-12515697-7a5c-4ed5-b84a-8d6b2070fb04.png)

**Comment by SeeFlowerX** [comment]
可能是因为`AppData\Roaming\GDA`下面有缓存导致的，试试清理下面这个文件夹的内容（当然这也可能导致一些GDA的设置、信息丢失，慎重操作）

**Comment by charles2gan** [comment]
> 利用apktool反编译apk修改包名后包名解析的还是修改前的包名，jadx解析没有问题 修改了反编译后的smali文件夹名字后gda解析的还是以前的包名，.smali文件本人也修改了的...
如SeeFlowerX所言，是缓存的原因，你可以到`AppData\Roaming\GDA`下找到apk同名的文件加格式如：apk文件名.apk_数字，把这个文件夹删除即可。

**Comment by dorry2015** [comment]
确实是缓存问题
