### ISSUE TITLE
[bug] 搜索输入框长度上限

### ISSUE THREAD

**Issue by SeeFlowerX** [charles2gan/GDA-android-reversing-Tool#137]
【Unexpected Behavior】

4.06使用中出现和以前不一样的行为，复制搜索结果好像是这两个版本才加的。

如果我点击输入框，也就是聚焦输入框，这个时候我想全选删除输入框的内容，Ctrl+A实际上会选中搜索结果。

---

【Free Version Limitation ?】

另外一个问题是，输入框只能输入一定长度的内容，如果复制的内容太长，那么粘贴将无效。

对于搜索package这个功能，非常受影响。

---

【Feature Request】

由于GDA没有全局搜索反编译结果或者说搜索smali的功能，对于某些内容很难定位。

比如我的使用场景是这样的：

想查找什么地方有用到DexClassloader，我只能通过关键词搜索，终于找到new DexClassloader，于是这个时候再去交叉引用，终于能看到交叉引用的情况了。

希望能够像jeb那样对smali结果进行全局搜索，或者提供一个输入签名进行交叉引用的功能。

**Comment by charles2gan** [comment]
感谢反馈：
问题1，2：下个版本修复并做改进。
问题3：GDA不采用全反编译后搜索，DexClassloader是属于API，你可以在BasicAnalyzer->AllAPIs中CTRL+F搜索来达到目的，然后交叉引用即可。

**Comment by SeeFlowerX** [comment]
感谢！
