### ISSUE TITLE
4.0.6 30s 提示没反应

### ISSUE THREAD

**Issue by z-houbin** [charles2gan/GDA-android-reversing-Tool#138]
加载大文件后出现30s提示，按了ok后只是关闭了对话框，并没有继续分析了，CPU毫无波动

**Comment by SeeFlowerX** [comment]
这种一般是apk有什么导致分析卡住了，出现这个弹窗后点取消反而会显示结果的，点ok并不会，你试一下。

**Comment by charles2gan** [comment]
可能是32位程序内存限制导致的。你看GDA的内存使用情况。

**Comment by z-houbin** [comment]
> 可能是32位程序内存限制导致的。你看GDA的内存使用情况。

内存在3720MB就没有动了，dy

**Comment by z-houbin** [comment]
> 这种一般是apk有什么导致分析卡住了，出现这个弹窗后点取消反而会显示结果的，点ok并不会，你试一下。

取消是可以用，但是后面还有很多没有加载出来

**Comment by charles2gan** [comment]
> > 可能是32位程序内存限制导致的。你看GDA的内存使用情况。
> 
> 内存在3720MB就没有动了，dy

已经达到32位程序的内存极限，点取消会终止继续加载分析，呈现的是已经反编译过的代码。
