### ISSUE TITLE
4.0.6搜索不到代码

### ISSUE THREAD

**Issue by dream0407** [charles2gan/GDA-android-reversing-Tool#140]
代码里明明有，但是GDA Searching却搜索不到，之前的版本可以搜索到

**Comment by aaronkingdom** [comment]
同样问题,  搜索字符串异常,  打开代码查看有很多,  却搜索不到

**Comment by lies2020** [comment]
4.08同样，比如这个APP：
https://www.wandoujia.com/apps/5773183
我想搜索哪里引用了0x7f080047，却怎样都搜不到，实际上这个数字存在于：
com.wifi99.android.locationcheater.databinding.ContentMainBinding.bind(View)

**Comment by lies2020** [comment]
4.08同样，比如这个APP：
https://www.wandoujia.com/apps/5773183
我想搜索哪里引用了0x7f080047，却怎样都搜不到，实际上这个数字存在于：
com.wifi99.android.locationcheater.databinding.ContentMainBinding.bind(View)

**Comment by SeeFlowerX** [comment]
GDA应该是没有做这部分资源的解析，这种用MT管理器操作方便点

**Comment by charles2gan** [comment]
> 4.08同样，比如这个APP： https://www.wandoujia.com/apps/5773183 我想搜索哪里引用了0x7f080047，却怎样都搜不到，实际上这个数字存在于： com.wifi99.android.locationcheater.databinding.ContentMainBinding.bind(View)

GDA目前的全局搜索无法对整型数字进行，也不支持一次性地将所有类/方法反编译后作为字符串数据进行匹配。

**Comment by lies2020** [comment]
> > 4.08同样，比如这个APP： https://www.wandoujia.com/apps/5773183 我想搜索哪里引用了0x7f080047，却怎样都搜不到，实际上这个数字存在于： com.wifi99.android.locationcheater.databinding.ContentMainBinding.bind(View)
> 
> GDA目前的全局搜索无法对整型数字进行，也不支持一次性地将所有类/方法反编译后作为字符串数据进行匹配。

个人认为反编译器搜索功能还是挺重要的，有助于快速定位代码，也希望GDA今后这方面能更完善强大，支持各类数据全局反编译搜索，同时支持资源的搜索

**Comment by charles2gan** [comment]
> 个人认为反编译器搜索功能还是挺重要的，有助于快速定位代码，也希望GDA今后这方面能更完善强大，支持各类数据全局反编译搜索，同时支持资源的搜索

感谢建议，后续考虑将你的建议纳入开发计划。

**Comment by Securee** [comment]
搜索功能的确可以进一步增强，比如提供正则表达式的搜索。当然jadx-gui使用之后它的正则表达式的搜索也不是很准确。

**Comment by charles2gan** [comment]
> 搜索功能的确可以进一步增强，比如提供正则表达式的搜索。当然jadx-gui使用之后它的正则表达式的搜索也不是很准确。

GDA支持正则搜索，见：4.4节：https://github.com/charles2gan/GDA-android-reversing-Tool/wiki
