### ISSUE TITLE
interface反编译错误

### ISSUE THREAD

**Issue by RandLily** [charles2gan/GDA-android-reversing-Tool#142]
JADX正常
![image](https://github.com/charles2gan/GDA-android-reversing-Tool/assets/48348945/b044c7e1-6bb2-495c-86eb-7bcf482546b8)
GDA反编译错误，但smali看起来是有的
![image](https://github.com/charles2gan/GDA-android-reversing-Tool/assets/48348945/3327e78c-baec-4c6b-9f80-c35837880092)
smali
![image](https://github.com/charles2gan/GDA-android-reversing-Tool/assets/48348945/40f34dde-25e3-4399-bba1-61d5a222c038)

**Comment by charles2gan** [comment]
谢谢反馈，提供下样本方便我快速定位问题，dex/apk皆可

**Comment by charles2gan** [comment]
你问题和这个问题可能是同一个问题，看这里就明白了。
https://github.com/charles2gan/GDA-android-reversing-Tool/issues/93

**Comment by charles2gan** [comment]
> [classes3.zip](https://github.com/charles2gan/GDA-android-reversing-Tool/files/12291204/classes3.zip) 自己写了一个，debug编译出来就能复现，看起来确实是default处理时的问题

感谢，此问题已修复，请关注下个版本。
