### ISSUE TITLE
4.09版本卡死在100%

### ISSUE THREAD

**Issue by anylayer** [charles2gan/GDA-android-reversing-Tool#145]
![image](https://github.com/charles2gan/GDA-android-reversing-Tool/assets/46556817/505d1983-7c91-44af-946d-f4c2d4bd042e)
![image](https://github.com/charles2gan/GDA-android-reversing-Tool/assets/46556817/663a2c8e-d90a-475f-995d-8313521b8590)
package: name='com.cibn.tv' versionCode='2121105102' versionName='11.5.1.2'

**Comment by anylayer** [comment]
再次打开apk又正常了

**Comment by charles2gan** [comment]
请不要再提这类问题，方法太多导致的。
