### ISSUE TITLE
GDA Not Recognize Classes

### ISSUE THREAD

**Issue by apkunpacker** [charles2gan/GDA-android-reversing-Tool#15]
https://github.com/CalebFenton/simplify/issues/140
Sample from this issue when decompile with GDA only show 1 class in L/ package while JEB show many more classes. So GDA simply not recognizing those classes

**Comment by charles2gan** [comment]
yours' a special package, where is apk/dex?

**Comment by apkunpacker** [comment]
please see above issue , sample is uploaded in last line of simplify issue

**Comment by charles2gan** [comment]
> please see above issue , sample is uploaded in last line of simplify issue

I have fixed the bug which is caused during the conversion from utf to multibyte, every failure char is '?', the next version will be fixed. thanks.

![image](https://user-images.githubusercontent.com/13128580/77851532-55a0d880-720c-11ea-9ff5-0a9f3851acff.png)

after deobfuscation:

![image](https://user-images.githubusercontent.com/13128580/77851597-97ca1a00-720c-11ea-813c-036e954ce871.png)
