### ISSUE TITLE
your dx version too low

### ISSUE THREAD

**Issue by muziling** [charles2gan/GDA-android-reversing-Tool#150]
drag an jar to gda, alert an dialog "your dx version too low"
this jar may compile with new android sdk d8.jar not dx.jar. 
how to decompile this jar？

**Comment by charles2gan** [comment]
Can you provide your sample

**Comment by muziling** [comment]
https://github.com/gaotianliuyun/gao/raw/master/jar/XYQ.jar

**Comment by charles2gan** [comment]
your jar file do not include the class file, there is only one dex file, changing your suffix .jar to .apk, try again.
