### ISSUE TITLE
查壳接口

### ISSUE THREAD

**Issue by CrossAcid** [charles2gan/GDA-android-reversing-Tool#155]
1.请问有完整的GDAInterface提供的接口函数文档嘛？最近想做一个自动化查壳脱壳的脚本，想试试能不能通过GDA的接口自动查壳
2.之前把douying拖进去加载的时间非常慢，很奇怪，不知道是什么原因

**Comment by charles2gan** [comment]
1.目前没有查壳的接口。
2.有可能是32位程序内存限制导致的。
