### ISSUE TITLE
Windows Issues

### ISSUE THREAD

**Issue by Nerixyz** [charles2gan/GDA-android-reversing-Tool#16]
There are some issues with the GDA window itself on windows.

- The "recent searches" window is not in its own window (so you can select it on the taskbar). It also appears on every desktop. 
 
- Clicking on the icon in the taskbar while the window is in focus doesn't do anything (it should be minimized).

- `ALT` and `space` doesn't do anything.

- The window isn't resizable.

- There's no dialog to save if there are changes/renamed variables once the application is closed.

- Not sure if it's really happening, but it feels like the window is still rendering while it can't be seen, so it needs more processing power.

Maybe there are more issues related to the window behaving different compared to others.

**Comment by socialAPIS** [comment]
Having the same issues.
And when i press x to see the calls to this function when i select a class or method and when i go back press again x and select another class i does nothing. It just stays in the same method.
Why you dont make gda open source? Leave your ego, my code is also bad but i post it
