### ISSUE TITLE
【BUG】在已经打开的搜索窗口中切换搜索的类型无效

### ISSUE THREAD

**Issue by SeeFlowerX** [charles2gan/GDA-android-reversing-Tool#160]
比如：先打开字符串的搜索，点击搜索；然后切换选择搜索方法，这个时候搜索存在的方法会没有结果。

推测是因为这种操作逻辑下，实际上还是搜索的字符串，而不是方法，只能关掉之后，点菜单的搜索方法按钮重新搜索。
![image](https://github.com/charles2gan/GDA-android-reversing-Tool/assets/70688581/651810c8-b1e4-481b-b32d-5229d1754bad)

**Comment by charles2gan** [comment]
感谢，已经加入修复列表，下个版本解决这个问题。

**Comment by SeeFlowerX** [comment]
虽然不知道这算不算bug...

GDA一直没有注解的那部分内容，然后今天发现字符串在注解里面的时候，也搜不到

后面有可能增加注解的部分吗

**Comment by charles2gan** [comment]
> 虽然不知道这算不算bug...
> 
> GDA一直没有注解的那部分内容，然后今天发现字符串在注解里面的时候，也搜不到
> 
> 后面有可能增加注解的部分吗

你的意思是annotation吗，的确这块我没有做解析，最开始设计的时候，认为annotation并不直接参与代码执行。我会好好考虑你的建议，后续有时间可以加上。

**Comment by SeeFlowerX** [comment]
感谢大大
