### ISSUE TITLE
Method/Property-Call Search

### ISSUE THREAD

**Issue by Nerixyz** [charles2gan/GDA-android-reversing-Tool#17]
When analyzing an apk, you not only have to find a class/string etc. but also calls to a method or property inside it. 
So for example Method `a()` calls `b()`. Then right clicking (or similar) could allow a search for calls to `b()` and then reveal the call in `a()`. The same for properties. Property `A.a` is accessed in `A.b()` for example.
This would improve the the speed of working with GDA.

**Comment by charles2gan** [comment]
see shortcut key carefully，guy！

**Comment by Nerixyz** [comment]
> see shortcut key carefully，guy，and read the Brief guide。

I'm talking about right clicking. Whenever you try out something it's more intuitive to right-click and then see the Keybindings and try them out.
