### ISSUE TITLE
Program detected by Windows Defender as Win32/Occamy.C trojan

### ISSUE THREAD

**Issue by Kungergely** [charles2gan/GDA-android-reversing-Tool#18]
So you've given some explanation about AV warnings being triggered by the "adb.exe file and the gdump file in %APPDATA%/GDA", however your explanation really doesn't add up. Windows still keeps detecting even the latest version (3.72) as containing Win32/Occamy.C (and not for an unpacked program called adb.exe, but in the executable, GDA3.72.exe itself!), which isn't really explained by the fact that the "bin file is packed by Themida". Instead it could be explained by the following line that I found in my netstat output after I ran the program:

```
  TCP    192.168.1.49:62250     123.112.20.158:9090    CLOSE_WAIT
 [GDA3.72.exe]
```

Why does your program try to connect to an IP in Beijing, CN (the IP of www.gda.wiki as I learned)?

**Comment by charles2gan** [comment]
www.gda.wiki is official website，that connection is used to check the new version。I won't explain the false positives of antivirus software。

**Comment by charles2gan** [comment]
You can use Wireshark to see the details of traffic。Below the latest version, you will be prompted as follows. official website:www.gda.wiki:9090.
[image](https://user-images.githubusercontent.com/13128580/79168147-bc80dd00-7e1b-11ea-9a62-417c3f4f2a56.png)
I just explain that these behaviors may lead to such results, Only GDA bin has protected by Themida, others, no. I don't want to be tired of explaining this kind of problem. I've explained it thousands of times.

**Comment by evildog1** [comment]
I hate when peoples 100% trusting on anti-virus. anti-virus are not perfect just like humans, there is no need to always trust it, especially when you are using reversing and modding tools. Some of my tools are flagged as malcious too because they are protected and are considered modding.

Like Malwarebytes are blocking all pirate sites and modding sites on porpuse just because they hate them

**Comment by Kungergely** [comment]
@evildog1 This a tad bit more than just it being flagged by an antivirus. First of all the fact that almost every AV software out there (not only Malwarebytes by far!) flags it is just the icing on the cake. What makes me personally much more suspicious is this fake repository (make no doubt about it: this repository does NOT contain any sources) and the fact that it's been compressed using an EXE packer.

Oh and one should be especially suspicious "when you are using reversing and modding tools", because quite a few of them contains a bit of some "extra stuff" (so to speak) which then the bastards (who develop them) use to take over the computers (and especially bank accounts) of wannabe hackers (usually frustrated, but naive teenagers).
