### ISSUE TITLE
Any chance for Linux support?

### ISSUE THREAD

**Issue by Shivelight** [charles2gan/GDA-android-reversing-Tool#2]
I tried wine and it doesn't work :cry:

**Comment by charles2gan** [comment]
maybe you should install MFC support library in wine, I haven't tested it yet in wine.

**Comment by AllanDaemon** [comment]
If we already have the source code, it likely to be running on Linux now.

**Comment by Shivelight** [comment]
I forgot about this issue. Yea I already install MFC support, and it still doesn't work.

**Comment by oahzuw** [comment]
install MFC Library  is ok,  command:   winetricks mfc42

**Comment by bl4ckh0l3z** [comment]
No news, bad news?! It would be great to have full support for Linux env...please... 🙏

**Comment by blshkv** [comment]
A native support would be highly appreciated 🙏
