### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by yhsnihao** [charles2gan/GDA-android-reversing-Tool#22]
在反编译某一款apk时，GDA闪退。apktool jadx jeb3都没问题，有点针对？
apk地址:链接：https://pan.baidu.com/s/1qrOBRgN21DE86P0du0jkbQ  提取码：r72e

**Comment by charles2gan** [comment]
回头我修复一下🙏

**Comment by charles2gan** [comment]
#fixed in gda3.73
