### ISSUE TITLE
unpacking apk

### ISSUE THREAD

**Issue by GSharma789** [charles2gan/GDA-android-reversing-Tool#3]
hi dev , packer detection is just awesome . if there can be a option to unpack those packers it will be a great work . thanks

**Comment by charles2gan** [comment]
that's hard work to unpack all those packers, some of which are stronger and stronger, some extract code, and some use virtualization technology. so GDA simply supports memory dumping of a process.

**Comment by GSharma789** [comment]
thats fine .nope , dumping is okay
