### ISSUE TITLE
Show Method Arguments in X-Ref 

### ISSUE THREAD

**Issue by Nerixyz** [charles2gan/GDA-android-reversing-Tool#34]
During compilation, some "pipelines" put commonly used strings in a global string "table" (or multiple). This "table" is essentially a big method with a switch-case statement deciding on the input which string to return.

<details><summary>Example</summary>

```java
public static String 9C4.A00(int p0)	//method@000f28
{
   switch (p0){	
       case 0:	
         return "null cannot be cast to non-null type android.view.ViewGroup";
       case 1:	
         return "DirectFragment.DIRECT_FRAGMENT_ARGUMENT_THREAD_ID";
       case 2:	
         return "null cannot be cast to non-null type android.app.Activity";
       case 3:	
         return "DirectFragment.ENTRY_POINT";
       case 4:	
         return "direct_quick_reply_camera_fragment";
       case 5:	
         return "onRealtimeEventPayload exception";
       case 6:	
         return "primary_button";
       // ...
   }
}
```
</details>

Now when using X-Ref, all the calls to this method are returned, but each call "requests" a different string. So one would need to check each call to find the use of a given string.

**Feature Request**

There are two possibilities for a solution that come to my mind.

1. **Inline these calls.** Which seems reasonable, but may not be desired by the user as the code gets changed. It seems like this could be done with a plugin/script.

2. **Show arguments to a method call.** This is the least destructive way of solving this: For _simple_ methods and method calls (only accepting a few arguments and all of them are primitives, and for calls: all arguments are static) show the call signature in the X-Ref window.

The window could show this for example: 
| methods | detail | calls |
| --- |---|---|
| someMethod | com.MyClass | `staticString(1, 2)` |
| otherMethod | com.MyClass | |

Code:
```java 
someMethod() {
    staticString(1, 2);
}
otherMethod() {
    staticString(1, getArgument());
}
```

**Comment by charles2gan** [comment]
be added in 3.85

**Comment by Nerixyz** [comment]
Thanks for adding this feature!
