### ISSUE TITLE
Does not deobfuscate

### ISSUE THREAD

**Issue by ghost** [charles2gan/GDA-android-reversing-Tool#35]
I try to deobfuscate small dex which was heavily obfuscated, but nothing was changed after it finished.
I am missing something?
[classes3.zip](https://github.com/charles2gan/GDA-android-reversing-Tool/files/5652855/classes3.zip)

**Comment by charles2gan** [comment]
It's works.
![image](https://user-images.githubusercontent.com/13128580/101461334-ad840780-3975-11eb-84fe-da6f62de28fd.png)

**Comment by Toshiba1127** [comment]
Ok I works, i had missed it
But method body and string still obfuscated tho. It have a lot of cases

**Comment by charles2gan** [comment]
After you deob it, you must `Refresh` the decompiled method with the right-click menu.
