### ISSUE TITLE
Search for exact string

### ISSUE THREAD

**Issue by Nerixyz** [charles2gan/GDA-android-reversing-Tool#37]
When searching for strings in an apk file, there's sometimes an exact camparison needed. In a relatively large app, searching e.g. for "update" will also return strings that include the word update (e.g. "updated", "will update"). This may exceed the capacity of the search, so matches are not shown.

My feature request would be that the search for a string would decide on what to check for:

`"update"` ➡ searches for exact strings of `update`
`update` ➡ searches for strings that _include_ `update`

Additionally, `/regex/i` could test the string against a regex (`/regex/i` would match "RegEx" and "regex" but not "reg ex").

**Comment by charles2gan** [comment]
Thank you for your suggestion, I'll add your suggested features to 3.88.

**Comment by kj9lj** [comment]
Instagram

**Comment by kj9lj** [comment]
Instagram
