### ISSUE TITLE
GDA Searching all Types Program is Crashing

### ISSUE THREAD

**Issue by Dielbach** [charles2gan/GDA-android-reversing-Tool#39]
If you click on GDA Searching and select all under Types, the program crashes!

**Comment by charles2gan** [comment]
Oh, it occurs when I introduce the regular expression matching feature in 3.88. the older version is ok.  I will fix the crash in the next version.

**Comment by hahanov** [comment]
@charles2gan , I ran into the problem, it is not possible to increase the `window size`, tried using Altmove but it does not help. This is a very strange decision on your part. In the search box too. How do I resize the window?
