### ISSUE TITLE
The exe triggers tons of malware warnings

### ISSUE THREAD

**Issue by superfr0** [charles2gan/GDA-android-reversing-Tool#4]
check virustotal

**Comment by charles2gan** [comment]
GDA will release the adb.exe and gdump, some av identify the behavior like a virus.

**Comment by AlirezaChegini** [comment]
Also because you used the Themida & WinLicense packer

**Comment by julianxhokaxhiu** [comment]
Agree, on Windows 10 it is not possible to run this app even if I whitelist the directory where it lives. It will complain that some "monitoring" software is on and I would need to turn it off ( referring to Windows Defender probably )
