### ISSUE TITLE
提示"计算机内存不足"的问题

### ISSUE THREAD

**Issue by hackren** [charles2gan/GDA-android-reversing-Tool#42]
目标apk：抖音_14.7.0
拖入apk到GDA3.90中，分析完成后提示"计算机内存不足",实际上此时计算机的内存占用率才30%左右。
GDA3.90之前的版本，均卡在99%的进度不动。希望能加以修复

**Comment by charles2gan** [comment]
默认情况下32位程序内存限制为2G，用命令editbin /largeaddressaware GDA3.95.exe 解除限制
