### ISSUE TITLE
Decompilation Bug

### ISSUE THREAD

**Issue by Nerixyz** [charles2gan/GDA-android-reversing-Tool#47]
I ran into a bug to which I don't quite know how to reproduce it.

I'm analyzing the version `177.0.0.30.119` from Instagram (x86) ([download here](https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-177-0-0-30-119-release/instagram-177-0-0-30-119-16-android-apk-download/)).

In the class `X.0bP`, method `A00`, the class `X.0cU` will be constructed. It's right after the switch statement (location `0313` in smali-view) in the method. This is where the problem lies. The smali code says, the class `X.0cU` should be constructed using `invoke-direct/range {v16 ... v38}`, so with arguments/parameters from `v17` to `v38`. But the Java-code only shows a "blank" constructor with no arguments.

There are also other bugs (probably) related to this. In instructions prior to this, you can see method calls whos value is immediately discarded such as `Boolean.valueOf(true)` or `Long.valueOf(...)`. Looking at the smali code, you can see that the return values of these are used to construct `X.0cU` (locations `02b8` and `02d4`).

However, looking at `X.0cU` directly reveals that the constructor takes seemingly no parameters. But the constructor body uses registers `v2` through `v22` to assign its class-members. 

I'm not sure where the root of this bug lies but it would be nice if this could be fixed.

**Comment by charles2gan** [comment]
the root of this bug is the signature of the construct method of X.0cU(actually LX/0cU;-><init>()V)，the number of args comes from the signature, I check it, and find the problem which I limited the number of args as 20. the next version will be fixed. thanks.
