### ISSUE TITLE
括号丢失反编译错误

### ISSUE THREAD

**Issue by wuxiaosu** [charles2gan/GDA-android-reversing-Tool#50]
& 和 << 在一起的时候括号会丢失导致实际运算变了
正确的应该是（jeb反编译）
out.write((p1.length & 1) << 7 | v2.length);
gda 反编译结果
out.write(p1.length & 1 << 7 | v2.length);

**Comment by charles2gan** [comment]
试试新版

**Comment by wuxiaosu** [comment]
3.92 已确认正常，感谢大佬
