### ISSUE TITLE
Tool-VunTester-load Ru->Run 框无法放大，打开是什么样的运行完放大还是什么样的，非常影响观察结果

### ISSUE THREAD

**Issue by xiaoxiaotu** [charles2gan/GDA-android-reversing-Tool#55]
Tool-VunTester-load Ru->Run 框无法放大，打开是什么样的运行完就是什么样的？非常影响观察结果
![image](https://user-images.githubusercontent.com/10893137/120575791-46db3480-c454-11eb-94e0-30359e664e15.png)

**Comment by charles2gan** [comment]
Fixed in GDA3.94
