### ISSUE TITLE
Add a Sanity Check for Renaming

### ISSUE THREAD

**Issue by Nerixyz** [charles2gan/GDA-android-reversing-Tool#56]
When renaming classes, GDA doesn't restrict one to use proper names.

So one could rename an item to `"my item"`. This breaks further renaming and X-Ref search (and probably other tools too).

It'd be nice to have a sanity check so one doesn't accidentally currupt the session/unsaved progress, by checking the name to not contain spaces or other invalid characters like dots.

**Comment by charles2gan** [comment]
Good advice. I've been overlooking this point. I'll add your advice in the next version.
