### ISSUE TITLE
反编译结果貌似不对

### ISSUE THREAD

**Issue by FreaxW** [charles2gan/GDA-android-reversing-Tool#61]
第一张图是反编译的代码，函数private static char[] a(byte[] p0,char[] p1)里面for循环下面的vi1和vi2应该是固定不变的，但是hook后从结果第二张图来看，实际上是全部都遍历到了的
![image](https://user-images.githubusercontent.com/46556817/126125478-404f7a05-2869-4849-bad5-b2d4495edb78.png)
![image](https://user-images.githubusercontent.com/46556817/126125937-ca9b26d3-406a-4531-bb87-193a878a024c.png)

**Comment by charles2gan** [comment]
可能是智能重命名的bug，取消即可

**Comment by charles2gan** [comment]
用最新版试一下
