### ISSUE TITLE
载入大文件好像还是有问题

### ISSUE THREAD

**Issue by 1padM1nI2** [charles2gan/GDA-android-reversing-Tool#63]
3.95版本，试了一下抖音最新版，要不就是卡住，要不就是闪退了

**Comment by 1padM1nI2** [comment]
还有个dump

链接：https://pan.baidu.com/s/1QGEnuMxDdx9YYaX0Zsv0tw 
提取码：41dq 
--来自百度网盘超级会员V4的分享

**Comment by charles2gan** [comment]
> 还有个dump
> 
> 链接：https://pan.baidu.com/s/1QGEnuMxDdx9YYaX0Zsv0tw
> 提取码：41dq
> --来自百度网盘超级会员V4的分享

OK

**Comment by charles2gan** [comment]
> 3.95版本，试了一下抖音最新版，要不就是卡住，要不就是闪退了

内存不足导致的，默认情况下32位程序内存限制为2G，用命令editbin /largeaddressaware GDA3.95.exe 解除限制
