### ISSUE TITLE
GDA3.96 合并语句时的一个逻辑错误

### ISSUE THREAD

**Issue by fallingx** [charles2gan/GDA-android-reversing-Tool#66]
![捕获](https://user-images.githubusercontent.com/53552096/131072971-f0caa44d-51dd-4c50-91a4-e08528ca8e47.PNG)
如图，应该是readShort()后赋值给变量h，然后if语句判断的是b的值
GDA3.96反编译时错误地合并了if和readShort语句，导致if判断的对象出错。
对比smali可知，左边jadx1.2的符合真正的逻辑

**Comment by charles2gan** [comment]
感谢，请提供一下apk文件

**Comment by fallingx** [comment]
> 感谢，请提供一下apk文件

提取了问题代码片段的apk和源码：
https://pan.baidu.com/s/1kzXQSFeQ22mSgA2LwjmBHA  提取码：0000
