### ISSUE TITLE
如何设置Python解释器的路径

### ISSUE THREAD

**Issue by FreaxW** [charles2gan/GDA-android-reversing-Tool#68]
情况是这样的，Frida hook有时候无法找到类，所有想通过虚拟环境切换其他版本的Frida，但是我没找到GDA如何设置Python的路径，请问目前GDA支持设置指定的Python解释器吗？

**Comment by FreaxW** [comment]
View->Env Config无效果，明明配置的是虚拟环境的目录，但是重新切换进去发现被换成config.dat，是需要把路径写在这个配置文件里面吗
![image](https://user-images.githubusercontent.com/46556817/132127093-92605f4c-5942-442f-8d35-690b3eeff43e.png)

**Comment by charles2gan** [comment]
这里有bug，回头我看看，感谢。
