### ISSUE TITLE
How to dump .so files

### ISSUE THREAD

**Issue by MrCoderAbhi** [charles2gan/GDA-android-reversing-Tool#69]
if there is any short video then we will be glad

**Comment by charles2gan** [comment]
Could this article help you?

https://github.com/charles2gan/GDA-android-reversing-Tool/wiki/GDA:-%22Unpacking-Decompiling-Decrypting%22-to-Capture-the-Flag-in-CTF-Game

When some errors occur, try it with this:

https://zhuanlan.zhihu.com/p/26341224
