### ISSUE TITLE
搜索关键信息后点击结果无法跳转，有人遇到这种情况吗

### ISSUE THREAD

**Issue by anylayer** [charles2gan/GDA-android-reversing-Tool#71]
经常出现搜索关键信息后点击结果无法跳转，查看后台进程，发现占用内存和cpu资源都很小，但是电脑就是很卡，是电脑的问题吗
![image](https://user-images.githubusercontent.com/46556817/133030640-b8c96f01-c506-4600-b369-3c53444c6142.png)

**Comment by fallingx** [comment]
目前最新版是3.96，也是我用的版本，也是同样的问题，并且问题还存在于交叉引用中。发生条件不明，但一种解决的办法先是搜索别的随便什么东西(交叉引用出问题则是先随便查找一个别的变量的交叉引用)，然后再查找本来要找的东西，就恢复正常了。
