### ISSUE TITLE
疑问？是否能导出成java文件？中文反编译问题？

### ISSUE THREAD

**Issue by programmeres** [charles2gan/GDA-android-reversing-Tool#77]
1.能直接全量导出成java文件么？
2.字节码里的显示字符串是这样的："\u0095\u000E\u0019\u00D0Z,\u0006U\u00CA\u00FA\u000F\u008E\u0010"，GDA解析成了这个"\xc2\x95\x0e\x19\xc3\x90Z,\x06U\xc3\x8a\xc3\xba\x0f\xc2\x8e\x10"？是bug？

**Comment by lake2** [comment]
> 1、目前没有提供这个功能 2、字节码里是UTF8编码，GDA用的是ascii

导出为java文件的功能 能否提供一下呢
