### ISSUE TITLE
GDA3.98修改类名后下次打开卡死

### ISSUE THREAD

**Issue by fallingx** [charles2gan/GDA-android-reversing-Tool#83]
复现问题的步骤为：
1.修改任意一个类的类名
2.修改该类的任意一个成员变量
3.保存退出
下次打开工程时就会在进度0%处卡死，cpu其中一核保持满载。

操作视频：
https://user-images.githubusercontent.com/53552096/142659125-5013433d-4c91-47ab-9246-3928b6153ada.mp4

视频中的程序和产生的工程文件：
[issue.zip](https://github.com/charles2gan/GDA-android-reversing-Tool/files/7571606/issue.zip)
程序的源码：同[#66](https://github.com/charles2gan/GDA-android-reversing-Tool/issues/66)

补充：
1.该问题从GDA3.97开始出现，GDA3.96及以下的版本进行视频中的操作不会有问题，视频中的工程文件在3.96及以下的版本也能够正常打开。发现该问题的起因是3.96的工程文件放在3.97和3.98版本中会在加载0%处卡住。
2.视频中操作的说明：
  (1)第一次打开GDA3.98：只修改了类名，但发现无法保存（退出时没有生成新的gda文件）
  (2)第二次打开GDA3.98：只修改了成员变量，发现能成功保存（退出时生成了gda文件）
  (3)第三次打开GDA3.98：先修改类名，再修改成员变量，退出时能保存，但下一次打开会卡死。

**Comment by charles2gan** [comment]
感谢提供详细的问题反馈，我已经定位到了bug并做了修复，请关注下一个版本。
