### ISSUE TITLE
部分方法不能反编译

### ISSUE THREAD

**Issue by lies2020** [charles2gan/GDA-android-reversing-Tool#85]
如图的方法不能反编译，连smali也不能看：
![2021-12-16_095715](https://user-images.githubusercontent.com/78834996/146301451-67d3749a-33cf-4cf0-a1aa-b61f890a48c4.jpg)
JEB能够反编译：
![2021-12-16_102846](https://user-images.githubusercontent.com/78834996/146301493-50b24a3d-e2b3-4b2f-b48e-f48780b99dd7.jpg)
以下是dex附件：
[cookie_6426764.zip](https://github.com/charles2gan/GDA-android-reversing-Tool/files/7724314/cookie_6426764.zip)

**Comment by charles2gan** [comment]
这个函数触发GDA的垃圾方法检测规则，所以没有做反编译。可能是混淆器生成或者用于对抗反编译器的方法。
