### ISSUE TITLE
Issue executing python script

### ISSUE THREAD

**Issue by Protolocoji** [charles2gan/GDA-android-reversing-Tool#86]
I'm trying to load a python script, but it fails with the following, any hints how that might be solved 🙏 ?

![image](https://user-images.githubusercontent.com/70773269/146843109-877a457f-a866-4070-8ab7-f33bf30570c7.png)

**PS**: I tried using java instead of Python, and the decompiler crashes when doing that

**Comment by charles2gan** [comment]
Try to change the py filename(don't use the test.py), and then load again.

**Comment by Protolocoji** [comment]
It worked! Thank you!
