### ISSUE TITLE
How to modify instructions directly?

### ISSUE THREAD

**Issue by Lixinist** [charles2gan/GDA-android-reversing-Tool#9]
I tried to modify the instruction directly (①) , but it had no effect. I can only modify bytecodes to modify instruction (②)
using GDA3.68
![QQ截图20191225172225](https://user-images.githubusercontent.com/43288377/71441253-b87d6200-273b-11ea-801e-a2a18d104592.png)

**Comment by charles2gan** [comment]
yes, you can only modify the the bytecodes at 1, and the opcode “const/4” at 2. And gda will update checksum and signature of dex. This is very old function that ‘s not upgraded in oldest version.
