### ISSUE TITLE
GDA3.9.8 对循环结构还原错误，JEB可正确还原

### ISSUE THREAD

**Issue by ssmnr** [charles2gan/GDA-android-reversing-Tool#90]
以下分别是GDA和JEB的还原结果，仔细对比了，错误应该出现在红框内的循环部分。

还有分支判断部分也是还原错了，

JEB
`  if(arg21.equals("DECODE")) {`

GDA
`str = "";
             if (str.equals(str5)) {`这个直接无用代码了

使用一样的输入，JEB还原的代码可得到与Hook相同的结果，GDA则不行。

![gda](https://user-images.githubusercontent.com/11171484/147968750-7d9c729e-a7ae-4ba1-9af2-72f39d3cba63.png)
![jeb](https://user-images.githubusercontent.com/11171484/147968765-c6f15d33-6fe7-4a19-a5fe-f7288fbac6e7.png)

希望大佬能解释下原因，学习一下，附上DEX
[classes2.zip](https://github.com/charles2gan/GDA-android-reversing-Tool/files/7803589/classes2.zip)

**Comment by charles2gan** [comment]
感谢反馈，是我的数据流分析算法存在bug，目前已经修复，请关注下一个版本的更新！
