### ISSUE TITLE
查找引用bug

### ISSUE THREAD

**Issue by xmhwws** [charles2gan/GDA-android-reversing-Tool#91]
apk link:https://drive.google.com/file/d/1LxQT_HBN92mIWIUpHWxKPKoEqzZsecEG/view?usp=sharing

搜索类:`oicq.wlogin_sdk.b.ac`
什么都搜索不到, 明明类存在
![2022-01-25_19-08-46](https://user-images.githubusercontent.com/42903751/150966161-f9cb5085-b2ed-46d8-b388-6cbf5dd18bf4.png)

对该类继承父类的成员变量this.h查找引用, 显示的结果很奇怪, 而且结果数量很少
![2022-01-25_19-10-31](https://user-images.githubusercontent.com/42903751/150966490-6987b7ba-d1ba-405b-b091-71f2bfd7475c.png)

In Jeb:
![jeb](https://user-images.githubusercontent.com/42903751/150966582-7978d976-4210-4b84-9467-c38185c85554.png)

发现GDA对于子类继承父类的成员变量和成员方法查找引用支持仍有bug;
![2022-01-25_19-14-28](https://user-images.githubusercontent.com/42903751/150966997-fe914846-90a7-4ffd-b139-a19fcce06a23.png)

**Comment by xmhwws** [comment]
补充: 继承父类的方法, 无法跳转过去
类:`oicq.wlogin_sdk.b.ar`
红框里面的几个方法是继承父类的, 双击无法跳转
![2022-01-25_22-05-36](https://user-images.githubusercontent.com/42903751/150991779-4f580665-8b5a-4ebf-95ce-256439630e9a.png)

**Comment by charles2gan** [comment]
前两个问题是你使用错误导致的：
第一个问题，搜索类名是不包含包的，要带包搜索选择package而不是class;
第二个问题，CTR+F是页内字符串搜索，成员变量不支持单独搜索，只支持交叉引用搜索。

第三个问题，目前无法直接跳转到继承自父类的成员，后续打算把此功能完善，感谢反馈。

**Comment by xmhwws** [comment]
> 第一个问题，搜索类名是不包含包的，要带包搜索选择package而不是class;

选择class进行搜索, 名为ac的类, 我只在结果中找到1个, 还不是我上面提到的, 所以搜索结果不全?

![2022-01-26_14-56-04](https://user-images.githubusercontent.com/42903751/151117471-5a593308-290b-480c-8d11-64f62becaa68.png)

> 第二个问题，CTR+F是页内字符串搜索，成员变量不支持单独搜索，只支持交叉引用搜索。

我使用的是交叉引用, 并非CTR+F, 我录制了一个时长48秒的gif动态图片, 作者可以看一下, 再自行测试下这个bug;

![录像3_转](https://user-images.githubusercontent.com/42903751/151118543-c0c32078-ec94-482a-a193-2364023b1060.gif)

**Comment by charles2gan** [comment]
希望你能仔细看完向导，你使用的姿势不对。
1.你可以采用精确匹配进行进行搜索，默认是模糊匹配。
2.交叉引用不能选中字符串，单击右键或者X即可。

**Comment by xmhwws** [comment]
感谢您的提醒, 我看了下github上的wiki

> 1.你可以采用精确匹配进行进行搜索，默认是模糊匹配。

ok, 使用精确匹配可以搜索得到那个类

![2022-01-26_18-29-48](https://user-images.githubusercontent.com/42903751/151152307-205f909b-7313-4da5-8e48-1807cfb25702.png)

如图所见, 有7个结果; 我用模糊匹配试了下, 我只能找到2个, 是否可以推测出GDA对搜索结果进行了删减?



> 2.交叉引用不能选中字符串，单击右键或者X即可，一旦选中代码字串做交叉引用意味着你在做页内代码搜索。

gif时长48秒, 请您再看一下; 因为我的操作是在`h`前和后各来一次右键交叉引用, 然后选中, 2次右键交叉引用;
我不知道哪里出了问题, 但我依旧希望您测试一下这块是否有bug;



3.数据流分析bug

对方法a数据流分析, 最下方理应还有个ret, 但显示的对话框没有, 且右侧没有滚动条
![2022-01-26_19-12-18](https://user-images.githubusercontent.com/42903751/151153522-9b76bd94-90fb-4eee-924f-a803c403f4bc.png)

**Comment by charles2gan** [comment]
问题1：是的，对于搜索结果过多的，会只显示前200条结果，因此，如果搜索结果太多，最好换精确匹配或者正则匹配；
问题2，3：前面疏忽了，我回头抽时间看看这个问题，争取下个版本修复，非常感谢！

**Comment by xmhwws** [comment]
GDA4.00 出来了
我测试了, 我觉得这个issue或许可能要reopen了@charles2gan

问题2
对该类继承父类的成员变量this.h查找引用, 显示的结果只有2个, 只显示当前类对其的交叉引用

![image](https://user-images.githubusercontent.com/42903751/159463856-1d01bd12-41d9-4dcc-90b8-a7da0c4893a8.png)

jadx:

![image](https://user-images.githubusercontent.com/42903751/159464147-d4959fb4-f8c4-4e83-bcfc-3f5adb27693d.png)

jeb也是100+个
我觉得这种非本类成员的变量, 交叉引用应该显示所有对它的调用;

新的问题4:
鼠标左键双击这个变量this.h,无法跳转到它的定义处;

![image](https://user-images.githubusercontent.com/42903751/159464717-b9a06f61-21df-4c48-8946-32ea4212f7f0.png)

新的问题5:
我对GDA的配色不是很了解, 
像上面的System.arraycopy是JDK的,无法跳转,用红色标注比较醒目;
这个方法`c`是继承自父类的,可以跳转过去;
私以为用正常的函数配色会比较好点? 因为红色一般修饰error

![image](https://user-images.githubusercontent.com/42903751/159465274-6bbfac12-8b1f-4a9a-94ae-db91ef909e7e.png)

新的问题6:
当我看过其他类,再来到ac类时,我在ac类里面点击了,但是最上面关于当前类的类名显示没有及时更新

![image](https://user-images.githubusercontent.com/42903751/159466309-9e0200da-c0ec-4eda-bd71-35a356f1f126.png)

**Comment by charles2gan** [comment]
感谢耐心反馈:
问题2，在设计时，也曾经考虑把继承自父类的成员做交叉引用，但是这种交叉引用是不准确的，在本类中使用的该成员只有交叉引用应该只存在于本类和本类子类中，以及本类的实例化对象中，兄弟类的同名成员不应该纳入到交叉引用中来，这是一种误导。因此，我对交叉引用做了做了限制，当然实际上这种限制导致部分无法识别的实例化对象中交叉应用丢失了。这块后续我看有没有更好方案解决。
问题4，这里潜藏了一个bug，下个版本修复。
问题5，识别API到不是难事，如果代码作色过程中对每个method做这种检测，会极大影响作色性能，暂时不考虑分开作色。如果对method的默认颜色不习惯，你可以通过菜单>View>SetColor来更换颜色。
问题6，上面三栏是当你点击到代码中的对象时用于显示对象详细信息的，不是用于显示当前类信息。

**Comment by xmhwws** [comment]
> 问题2，在设计时，也曾经考虑把继承自父类的成员做交叉引用，但是这种交叉引用是不准确的，一个成员的交叉引用应该只存在于本类和本类子类中，以及本类的实例化对象中。兄弟类的同名成员不应该纳入到交叉引用中来，这是一种误导。因此，我对交叉引用做了做了限制，当然实际上这种限制导致部分无法识别的实例化对象中交叉应用丢失了。这块后续我看有没有更好方案解决。

问题2 关键是这个成员变量是来自同一个包, 它本质上不属于当前类, 当前类可以看做是子类
它的父类(包)定义了它, 父类(包) 下面很多子类调用/修改了它
那是否应该显示所有对它的调用呢?

同类型的反编译器比如jadx/jeb都选择了显示所有调用, 因为交叉引用是比较重要的部分, 如果结果不全, 很容易让人忽略一些可能是关键点的地方

我觉得这是一个比较有争议的事, 建议作者开放一个选项, 让用户自行选择, 多谢@charles2gan

**Comment by charles2gan** [comment]
你要分清楚类和实例，在程序执行时，修改的是实例的成员，不是类的成员(静态除外)，这块之所以重要，是因为一个类的成员是否真实被使用直接影响到数据流分析(污点分析传播分析和隐私泄露检测)的可靠性。后续会把你的建议纳入考虑范围内。再次感谢
