### ISSUE TITLE
GDA插件的一些问题

### ISSUE THREAD

**Issue by zzhichen** [charles2gan/GDA-android-reversing-Tool#92]
你好，这两天发现有插件功能就试用了下。发现3.99版本的一些问题：
1. 在python脚本获取类的代码时有时会出现获取到code是空字符串。在比较大的apk时会出现这种情况。
2. 每次修改了python脚本，在GDA里点File-Run Python好像都是执行修改前的python脚本，是不是有缓存问题？修改了python脚本都需要把python脚本重命名或者重新打开GDA 才能正确执行修改后的python脚本。
3. java脚本就没有成功执行过，而且是用的自带的java脚本例子。每次打开GDA第一次运行java脚本会报：[ERROR] Can't find pClassInfo，后面都报：load failure! 

我安装的python27 32位版本，jdk是 java version "1.7.0_79" 32位版本，设置了jvm.dll路径。

**Comment by charles2gan** [comment]
感谢反馈：
1. 希望能够提供apk及类路径
2. 这个问题在下一个版本修复
3. 运行的例子里必须带com包下的文件，确认类com.gda.api.ClassInfo是否存在

**Comment by zzhichen** [comment]
你好 我重新试了下 奇怪 现在没复现code是空，不过出现以下问题导致崩溃。

exception: access violation reading 0xFFFFFFFF
#Traceback (most recent call last):
#   File F:\\soft\\GDA\\dumpJava7.py line 20 in GDA_MAIN
#    code = gda.GetClassCodeById_Ex(classCode.idx)
#   File F:\\soft\\GDA\\GdaImport.py line 155 in GetClassCodeById_Ex
#    return self.GetClassCodeById_Ex_(idxdexId)
# WindowsError: exception: access violation reading 0xFFFFFFFF

写的脚本和apk包链接
https://www.aliyundrive.com/s/nC9Qm4P7E9Y

**Comment by charles2gan** [comment]
这个崩溃的问题找到，修复在下个版本里，感谢
