### ISSUE TITLE
default修饰的的接口类的方法可以有方法体

### ISSUE THREAD

**Issue by xmhwws** [charles2gan/GDA-android-reversing-Tool#93]
win10
java8

apk链接: https://drive.google.com/file/d/1OplzQllsMzovaCyTCvyclm4_iNuLfHea/view?usp=sharing
类名:com.xi.servicedemo.interfaces.ICommunication

java8中有个关键字default,它可以使接口类的方法有方法体;
我写了一份测试代码:

![2022-02-08_13-46-28](https://user-images.githubusercontent.com/42903751/152928313-7fd6c272-2cbf-4815-a24a-5e237fae92ab.png)

但反编译显示如下:

![2022-02-08_14-08-52](https://user-images.githubusercontent.com/42903751/152928370-df7d92a5-c402-448b-a239-3f861e01bc33.png)

总感觉显示的有些反人类

**Comment by charles2gan** [comment]
GDA为了保留java的一些底层机制，没有做内部类的合并。这里涉及到接口的default修饰的底层机制，如果采用default修饰实现了接口的方法，java编译器会默认生成一个内部类-CC来完成接口的实现，如果你了解底层的一些知识就不会觉得奇怪了。

**Comment by xmhwws** [comment]
ok, 此问题关闭
好奇问一句, 类似这种看上去有点奇怪的, 有哪些? 可以细说吗?

**Comment by charles2gan** [comment]
> ok, 此问题关闭 好奇问一句, 类似这种看上去有点奇怪的, 有哪些? 可以细说吗?

这和一些新java版本的特性有关，目前我也没有专门去研究这个问题，GDA反编译保留了一些底层特性，正好可以去研究这些新特性的底层实现。
